# Minha solução
algo = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('Está em maiúsculas? {}'.format(algo.isupper()))
print('Está em minúsculas? {}'.format(algo.islower()))
print('Está capitalizada? {}'.format(algo.istitle()))

# Solução de Gustavo Guanabara (CursoemVideo)
# a = input('Digite algo: ')
# print('O tipo primitivo desse valor é ', type(a))
# print('Só tem espaços? ', a.isspace())
# print('É um número?', a.isnumeric())
# print('É alfabético? ', a.isalpha())
# print('É alfanumérico? ', a.isalnum())
# print('Está em maiúsculas? ', a.isupper())
# print('Está em minúsculas? ', a.islower())
# print('Está capitalizada? ', a.istitle())
